### PR TITLE
Fix a bug that causes merge to fail if any Jarfile defines an exclude rule

### PR DESCRIPTION
**Pull request by pangloss**

### CODE REVIEW

**Comment by pangloss** [comment]
I'd really appreciate it if you could push this out as a new release. I've got a project that relies on it to release pending this fix. Thanks!

**Comment by mguymon** [comment]
looks good, ill push a release.

**Comment by mguymon** [comment]
part of the 0.10.4 gem

**Comment by pangloss** [comment]
Thanks!

**Pull request merged**
